apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    image.redhat.com/generate: "true"
    appstudio.openshift.io/pac-provision: request
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac
  name: knative-eventing-channel-dispatcher-release-next
spec:
  componentName: knative-eventing-channel-dispatcher
  application: serverless-operator-release-next
   
  source:
    git:
      url: https://github.com/openshift-knative/eventing.git
      context: 
      dockerfileUrl: openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
      revision: release-next
