apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac-no-mr
  name: kn-eventing-channel-dispatcher-115
spec:
  componentName: kn-eventing-channel-dispatcher-115
  application: serverless-operator-135
   
  source:
    git:
      url: https://github.com/openshift-knative/eventing.git
      context: 
      dockerfileUrl: openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
      revision: release-v1.15
